fs:
  image: coaxial/freeswitch:for_adhearsion
  entrypoint: /usr/src/freeswitch_conf/start.sh
  volumes:
    - lib/freeswitch_conf:/usr/src/freeswitch_conf:ro
    - log:/var/log:rw
  ports:
    # The port mod_rayo is listening on
    - "5222:5222"
    # SIP Internal
    - "5060:5060"
    - "5060:5060/udp"
    # SIP External
    - "5080:5080"
    - "5080:5080/udp"
    # RTP ports
    - "16384:16384/udp"
    - "16385:16385/udp"
    - "16386:16386/udp"
    - "16387:16387/udp"
    - "16388:16388/udp"
    - "16389:16389/udp"
    - "16390:16390/udp"
    - "16391:16391/udp"
    - "16392:16392/udp"
    - "16393:16393/udp"
    - "16394:16394/udp"
    - "16395:16395/udp"
    - "16396:16396/udp"
    - "16397:16397/udp"
    - "16398:16398/udp"
    - "16399:16399/udp"
    - "16400:16400/udp"
    - "16401:16401/udp"
    - "16402:16402/udp"
    - "16403:16403/udp"
    - "16404:16404/udp"
    - "16405:16405/udp"
    - "16406:16406/udp"
    - "16407:16407/udp"
    - "16408:16408/udp"
    - "16409:16409/udp"
    - "16410:16410/udp"
    - "16411:16411/udp"
    - "16412:16412/udp"
    - "16413:16413/udp"
    - "16414:16414/udp"
    - "16415:16415/udp"
    - "16416:16416/udp"
    - "16417:16417/udp"
    - "16418:16418/udp"
    - "16419:16419/udp"
    - "16420:16420/udp"
    - "16421:16421/udp"
    - "16422:16422/udp"
    - "16423:16423/udp"
    - "16424:16424/udp"
    - "16425:16425/udp"
    - "16426:16426/udp"
    - "16427:16427/udp"
    - "16428:16428/udp"
    - "16429:16429/udp"
    - "16430:16430/udp"
    - "16431:16431/udp"
    - "16432:16432/udp"
    - "16433:16433/udp"
    - "16434:16434/udp"
    - "16435:16435/udp"
    - "16436:16436/udp"
    - "16437:16437/udp"
    - "16438:16438/udp"
    - "16439:16439/udp"
    - "16440:16440/udp"
    - "16441:16441/udp"
    - "16442:16442/udp"
    - "16443:16443/udp"
    - "16444:16444/udp"
    - "16445:16445/udp"
    - "16446:16446/udp"
    - "16447:16447/udp"
    - "16448:16448/udp"
    - "16449:16449/udp"
    - "16450:16450/udp"
    - "16451:16451/udp"
    - "16452:16452/udp"
    - "16453:16453/udp"
    - "16454:16454/udp"
    - "16455:16455/udp"
    - "16456:16456/udp"
    - "16457:16457/udp"
    - "16458:16458/udp"
    - "16459:16459/udp"
    - "16460:16460/udp"
    - "16461:16461/udp"
    - "16462:16462/udp"
    - "16463:16463/udp"
    - "16464:16464/udp"
    - "16465:16465/udp"
    - "16466:16466/udp"
    - "16467:16467/udp"
    - "16468:16468/udp"
    - "16469:16469/udp"
    - "16470:16470/udp"
    - "16471:16471/udp"
    - "16472:16472/udp"
    - "16473:16473/udp"
    - "16474:16474/udp"
    - "16475:16475/udp"
    - "16476:16476/udp"
    - "16477:16477/udp"
    - "16478:16478/udp"
    - "16479:16479/udp"
    - "16480:16480/udp"
    - "16481:16481/udp"
    - "16482:16482/udp"
    - "16483:16483/udp"
    - "16484:16484/udp"

ahn:
  image: coaxial/adhearsion
  volumes:
    - .:/usr/src/app
  command: /usr/src/app/lib/ahn/start.sh
  links:
    - fs

